# Generated by Django 4.2.4 on 2024-03-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
