# Generated by Django 4.2.4 on 2024-03-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menu_item_is_veg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_item',
            name='is_veg',
        ),
    ]
